### ISSUE TITLE
Question about output of ProPCA

### ISSUE THREAD

**Issue by biona001** [sriramlab/fastPPCA#15]
I computed top 5 PCs on simulated data with 5500 samples and 50000 SNPs. The command was `propca -g sim -o pca_ -seed 1` which generated 3 outputs `pca_projections.txt`, `pca_evals.txt`, `pca_evecs.txt`. 

I kind of expected the last one `pca_evecs.txt` to contain the 5500 by 5 matrix of PCs, but it was a 50000 by 5 matrix. On the other hand, `pca_projections.txt` is 5500 by 5, and I wonder whether this is the actual file with the PCs? Am I misunderstanding something?

**Comment by alecmchiu** [comment]
Hi Ben,

The formulation for PCA in ProPCA and several other PCA softwares for genotypes are that the genotype matrix is M x N, where M is the number of SNPs and N is the number of individuals (this is also how PLINK stores the genotypes in the binary BED files). As such, the principal components / eigenvectors are stored in `_evecs.txt` correspond to the number of SNPs while the samples projected onto the PCs are in `_projections.txt`.

**Comment by biona001** [comment]
Hi Alec, thanks for the clarification.
