### ISSUE TITLE
Report EigenValues instead of Singular values

### ISSUE THREAD

**Issue by aagrxyz** [sriramlab/fastPPCA#3]
fastPPCA presently reports the singular values rather than the normalized eigenvalues.

Rescaling the fastPPCA eigenvalues by 1/sqrt(n) should fix this.

**Comment by sriramsr** [comment]
Please fix the code so that it outputs this.

Thanks,
Sriram

**Comment by aagrxyz** [comment]
Fixed with d123be0c182f9b928dd248de8bf8f1106a6bbf6f
